---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: task2-config
data:
  APP_PORT: 8080
  DB_HOST: postgreqsl
  DB_PORT: 5432
  DB_NAME: db_task1
  DB_USER: postgresql

---
apiVesion: v1
kind: Secret
metadata:
  name: task2-secret
data:
  DB_PASSWORD:

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task2-deploy
spec:
  selector:
    matchLabels:
      app: task2-app
  replicas: 2
  template:
    metadata:
      labels:
        app: task2-app
    spec:
      containers:
      - name: task2-pod
        image: docker.io/guzarov/otus-arch:task2-spring
        ports:
          - containerPort: 8000
        livenessProbe:
          httpGet:
            port: 8000
            path: /actuator/health/liveness
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            port: 8000
            path: /actuator/health/readiness
          initialDelaySeconds: 10
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: task2-service
spec:
  selector:
    app: task2-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: task2-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: arch.homework
    http:
      paths:
        - path: /otusapp/guzarov($|/)(.*)
          pathType: Prefix
          backend:
            service:
              name: task2-service
              port: 
                number: 8000
