create table if not exists tbl_user
(
	id bigint generated by default as identity
		constraint tbl_user_pkey
			primary key,
	email varchar(255),
	first_name varchar(255),
	last_name varchar(255),
	phone varchar(255),
	username varchar(255)
);

