---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "task3-chart.fullname" . }}
  labels:
    {{- include "task3-chart.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    {{- include "task3-chart.selectorLabels" . | nindent 4 }}
