---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: {{ include "task2-chart.fullname" . }}
data:
  APP_PORT: "8000"
  DB_HOST: "{{ .Values.postgresqlHost }}"
  DB_NAME: "{{ .Values.postgresqlDatabase }}"
  DB_USER: "{{ .Values.postgresqlUsername }}"

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "task2-chart.fullname" . }}
data:
  DB_PASSWORD: {{ printf .Values.postgresqlPassword | b64enc | quote }}
  