---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: task2-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: {{ .Values.application.host }}
    http:
      paths:
        - path: /otusapp/guzarov($|/)(.*)
          pathType: Prefix
          backend:
            service:
              name: {{ include "task2-chart.fullname" . }}
              port: 
                number: {{ .Values.application.port }}
