---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "task2-chart.fullname" . }}
  labels:
    {{- include "task2-chart.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    {{- include "task2-chart.selectorLabels" . | nindent 4 }}
